# This is a basic workflow to help you get started with Actions
#------------------------------------#
GitHub Actions Part-1 - Basics
#------------------------------------#



name: My-GitHubActions-Basics

# Controls when the action will run. 
on: 
  push:
    branches: 
      - main
      
jobs:
  my_testing:
    runs-on : ubuntu-latest
    
    steps:
    - name : Print Hello Message
      run  : echo "Hello World from Testing job"

   my_deploy: 
      runs on : ubuntu-latest
     
      steps:
      - name : Print Hello Message
        run  : echo "Hello World from Deploy job"
          
          
          
          
          
          
          
          
          
          
          
          
          echo test, and deploy your project.
