# This is a basic workflow to help you get started with Actions
#------------------------------------#
# GitHub Actions Part-1 - Basics
#------------------------------------#

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME     : "MyFlask"
  DEPLOY_PACKAGE_NAME  : "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - main
      
jobs:
  my_testing:
    runs-on : ubuntu-latesttttt
    
    steps:
    - name : Print Hello Message in Testing
      run  : echo "Hello World from Testing job"
      
    - name: Execute few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
    - name: List current folder
      run : ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run : ls -la
      
  my_deploy: 
    runs-on : ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "This is Job Level Variable 1"
      VAR2 : "This is Job Level Variable 2"     
    
    steps:
    - name : Print Hello Message in Deploy
      run  : echo "Hello World from Deploy job"
      
    - name: Print env vars
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
        
      env:
        LOCAL_VAR: "This is Local Variable"
       
    - name: Printing Deployment Package
      run : echo "Deploy Package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
    - name: Lets test some packages if they are here 1
      run : aws --version
          
    - name: Lets test some packages if they are here 1
      run : zip     
          
          
          
          
          
          
          
          
          
          echo test, and deploy your project.
